
version: '3'

services:
  frontend: 
    build: ./frontend
    ports:
      - 3000:3000
  backend: 
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emp
    volumes:
      - db-data:/var/lib/mysql

  
volumes:
  db-data: